Bugfix: screen command uses minecraft as screen name as default
Signed-off-by: bjanssens <bjanssens@inuits.eu>

diff --git a/templates/init_script.erb b/templates/init_script.erb
--- a/templates/init_script.erb
+++ b/templates/init_script.erb
@@ -18,7 +18,7 @@
 
 #Settings
 SERVICE='minecraft_server.<%= @version %>.jar'
-SCREENNAME = '<%= @service_name %>'
+SCREENNAME='<%= @service_name %>'
 OPTIONS='<%= @server_options %>'
 USERNAME='<%= @user %>'
 WORLD='<%= @level_name %>'
@@ -48,13 +48,13 @@ mc_start() {
  else
    echo "Starting $SERVICE..."
    cd $MCPATH
-   as_user "cd $MCPATH && screen -h $HISTORY -dmS minecraft $INVOCATION"
+   as_user "cd $MCPATH && screen -h $HISTORY -dmS ${SCREENNAME} $INVOCATION"
    sleep 7
    if pgrep -u $USERNAME -f $SERVICE > /dev/null
    then
-     echo "$SERVICE is now running."
+     echo "$SERVICE is now running." && exit 0
    else
-     echo "Error! Could not start $SERVICE!"
+     echo "Error! Could not start $SERVICE!" && exit 1
    fi
  fi
 }
@@ -63,9 +63,9 @@ mc_saveoff() {
  if pgrep -u $USERNAME -f $SERVICE > /dev/null
  then
    echo "$SERVICE is running... suspending saves"
-   as_user "screen -p 0 -S $SCREENNAME -X eval 'stuff \"say SERVER BACKUP STARTING. Server going readonly...\"\015'"
-   as_user "screen -p 0 -S $SCREENNAME -X eval 'stuff \"save-off\"\015'"
-   as_user "screen -p 0 -S $SCREENNAME -X eval 'stuff \"save-all\"\015'"
+   as_user "screen -p 0 -S ${SCREENNAME} -X eval 'stuff \"say SERVER BACKUP STARTING. Server going readonly...\"\015'"
+   as_user "screen -p 0 -S ${SCREENNAME} -X eval 'stuff \"save-off\"\015'"
+   as_user "screen -p 0 -S ${SCREENNAME} -X eval 'stuff \"save-all\"\015'"
    sync
    sleep 10
  else
@@ -77,8 +77,8 @@ mc_saveon() {
  if pgrep -u $USERNAME -f $SERVICE > /dev/null
  then
    echo "$SERVICE is running... re-enabling saves"
-   as_user "screen -p 0 -S $SCREENNAME -X eval 'stuff \"save-on\"\015'"
-   as_user "screen -p 0 -S $SCREENNAME -X eval 'stuff \"say SERVER BACKUP ENDED. Server going read-write...\"\015'"
+   as_user "screen -p 0 -S ${SCREENNAME} -X eval 'stuff \"save-on\"\015'"
+   as_user "screen -p 0 -S ${SCREENNAME} -X eval 'stuff \"say SERVER BACKUP ENDED. Server going read-write...\"\015'"
  else
    echo "$SERVICE is not running. Not resuming saves."
  fi
@@ -88,19 +88,19 @@ mc_stop() {
  if pgrep -u $USERNAME -f $SERVICE > /dev/null
  then
    echo "Stopping $SERVICE"
-   as_user "screen -p 0 -S $SCREENNAME -X eval 'stuff \"say SERVER SHUTTING DOWN IN 10 SECONDS. Saving map...\"\015'"
-   as_user "screen -p 0 -S $SCREENNAME -X eval 'stuff \"save-all\"\015'"
+   as_user "screen -p 0 -S ${SCREENNAME} -X eval 'stuff \"say SERVER SHUTTING DOWN IN 10 SECONDS. Saving map...\"\015'"
+   as_user "screen -p 0 -S ${SCREENNAME} -X eval 'stuff \"save-all\"\015'"
    sleep 10
-   as_user "screen -p 0 -S $SCREENNAME -X eval 'stuff \"stop\"\015'"
+   as_user "screen -p 0 -S ${SCREENNAME} -X eval 'stuff \"stop\"\015'"
    sleep 7
  else
    echo "$SERVICE was not running."
  fi
  if pgrep -u $USERNAME -f $SERVICE > /dev/null
  then
-   echo "Error! $SERVICE could not be stopped."
+   echo "Error! $SERVICE could not be stopped." && exit 1
  else
-   echo "$SERVICE is stopped."
+   echo "$SERVICE is stopped." && exit 0
  fi
 } 
 
@@ -162,7 +162,7 @@ mc_command() {
  then
    pre_log_len=`wc -l "$MCPATH/logs/latest.log" | awk '{print $1}'`
    echo "$SERVICE is running... executing command"
-   as_user "screen -p 0 -S $SCREENNAME -X eval 'stuff \"$command\"\015'"
+   as_user "screen -p 0 -S ${SCREENNAME} -X eval 'stuff \"$command\"\015'"
    sleep .1 # assumes that the command will run and print to the log file in less than .1 seconds
    # print output
    tail -n $[`wc -l "$MCPATH/logs/latest.log" | awk '{print $1}'`-$pre_log_len] "$MCPATH/logs/latest.log"
